- src/Cell.js
- src/Scrollbar.js
- src/Table.js
> Fix: The position was updated incorrectly when the scrollbar was clicked on <Table>

- package-lock.json
- package.json
- src/Table.js
Fix: https://github.com/rsuite/rsuite/issues/234
> Fixed a passively triggered onScroll event that caused the scrollbar to be misaligned

- README.md
Just the docs fix, since it's undocumented (at least, i was not able to find it :) )
> Added locale prop in docs

- src/Table.js
https://www.chromestatus.com/features/6662647093133312
> Fix: Unable to preventDefault inside passive event listener due to target being treated as passive

- src/Table.js
https://github.com/rsuite/rsuite/issues/629
> Fixed a problem with scrolling white screen after changing height

- package.json
- src/CellGroup.js
- src/Row.js
- src/Scrollbar.js
- src/Table.js
- src/constants.js
- src/utils/index.js
- src/utils/translateDOMPositionXY.js
https://github.com/rsuite/rsuite/issues/628
> Fixed a rendering error when the column in the table was null

- src/Table.js
FIx: https://github.com/rsuite/rsuite/issues/683
> Fixed scroll position after data update

- src/Table.js
Fix: https://github.com/rsuite/rsuite-table/issues/102
> Fix _constants is not defined

- src/Cell.js
- src/Table.js
Fix: https://github.com/rsuite/rsuite/issues/729
Fix: https://github.com/rsuite/rsuite-table/issues/107
> Fix Table does not support RTL

- src/Table.js
- src/utils/getRandomKey.js
- src/utils/index.js
Improve:
- https://github.com/rsuite/rsuite-table/issues/91
- https://github.com/rsuite/rsuite-table/issues/113
> Improve the performance of virtualized table

- src/ColumnResizeHandler.js
- src/HeaderCell.js
- src/Table.js
Fix:
https://github.com/rsuite/rsuite/issues/776
https://github.com/rsuite/rsuite/issues/778
> Fix RTL related bugs

- CHANGELOG.md
- README.md
- docs/md/TreeTable.md
- src/Cell.d.ts
- src/Cell.tsx
- src/Column.d.ts
- src/Table.tsx
- src/TableContext.tsx
- test/TableSpec.js
Fix: https://github.com/rsuite/rsuite/issues/861
> Added support `treeCol` on `<Column>`

- CHANGELOG.md
- README.md
- docs/md/EditTable.md
- docs/md/TreeTable.md
- src/Cell.d.ts
- src/Cell.tsx
- src/Table.d.ts
- src/Table.tsx
- test/TableSpec.js
Fix: https://github.com/rsuite/rsuite-table/issues/126
> Added `expanded` parameter in `renderTreeToggle`

- README.md
- docs/md/DynamicTable.md
- src/Table.d.ts
- src/Table.tsx
Fix: https://github.com/rsuite/rsuite-table/issues/139
Fix:https://github.com/rsuite/rsuite/issues/964
> Support `onDataUpdated` on `<Table>`

- docs/md/LargeLists.md
- src/Table.tsx
Fix: https://github.com/rsuite/rsuite/issues/1044
> fix(Table): Fix rsuite#1044

- README.md
> Note about nested data

- src/ColumnGroup.tsx
fix: https://github.com/rsuite/rsuite/issues/1312
> Fix @rsuite#1312

- README.md
- src/CellGroup.tsx
- src/Row.tsx
fix: https://github.com/rsuite/rsuite-table/issues/160
> Fix not working with `gatsbyjs`

- src/Table.tsx
fix: https://github.com/rsuite/rsuite/issues/1436
> fix(affixHeader): Fix the table height problem caused by affixHeader

- package.json
> add cross-env to dev scripts

- src/Table.tsx
- src/less/table.less
- src/utils/resetLeftForCells.ts
Fix: https://github.com/rsuite/rsuite/issues/1446
> Fixed the unhandled scroll bar width when the Cell is fixed on the right

- src/ColumnGroup.d.ts
- src/ColumnGroup.tsx
- test/ColumnGroupSpec.js
fix: https://github.com/rsuite/rsuite-table/issues/183
> Fix ColumnGroup does not support `classPrefix`

- docs/md/ResizableColumnTable.md
- src/ColumnResizeHandler.d.ts
- src/ColumnResizeHandler.tsx
- src/HeaderCell.d.ts
- src/HeaderCell.tsx
- src/Table.tsx
- src/constants.ts
- test/ColumnResizeHandlerSpec.js
> feat(resize): Honor minWidth setting when resizing columns.

- package.json
- src/Table.tsx
- test/TableSpec.js
fix: https://github.com/rsuite/rsuite/issues/1532
> fix(Table): Fix that the `ColumnGroup` array cannot be rendered in the Table

- examples/with-gatsby/src/pages/index.js
- src/Cell.tsx
- src/CellGroup.tsx
- src/ColumnResizeHandler.tsx
- src/HeaderCell.tsx
- src/Row.tsx
- src/Scrollbar.tsx
- src/Table.tsx
- src/utils/getUnhandledProps.ts
fix https://github.com/rsuite/rsuite-table/issues/208
> fix(propTypes): fix unable to get propTypes after gatsby is compiled

- docs/md/ColumnGroupTable.md
- src/Cell.tsx
- src/ColumnGroup.tsx
- src/HeaderCell.tsx
- src/Table.tsx
- src/less/column-group.less
- src/utils/mergeCells.tsx
- test/CellSpec.js
- test/ColumnGroupSpec.js
- test/TableSpec.js
fix: https://github.com/rsuite/rsuite-table/issues/198
> fix(ColumnGroup): fix column cannot be sorted in ColumnGroup

- docs/md/AffixHorizontalScrollbar.md
- src/utils/useAffix.ts
fix https://github.com/rsuite/rsuite/issues/1716
> fix(affix): fix scrollbar not re-rendering after data update

- README.md
- docs/md/ColumnGroupTable.md
- src/Cell.tsx
- src/ColumnGroup.tsx
- src/utils/getTableColumns.ts
- src/utils/mergeCells.tsx
- test/ColumnGroupSpec.js
fix https://github.com/rsuite/rsuite/issues/1444
> feat(ColumnGroup): support `groupHeaderHeight` on `<ColumnGroup>`

- docs/md/AutoHeightTable.md
- src/utils/useTableDimension.ts
fix https://github.com/rsuite/rsuite/issues/1583
> fix(autoHeight): fix the extra scroll bar width after autoHeight

- docs/md/Expanded.md
- docs/md/FixedColumnTable.md
- docs/md/TreeTable.md
- docs/md/UpdateData.md
- src/utils/useScrollListener.ts
- test/TableSpec.js
> fix(table): fix scroll listener not updated after data update

- docs/md/Expanded.md
- docs/md/WordWrapTable.md
- src/utils/useTableRows.ts
fix https://github.com/rsuite/rsuite/issues/1686
> fix(table): fix cell text does not wrap when `wordWrap`

- docs/md/TreeTable.md
- package-lock.json
- package.json
- src/ColumnResizeHandler.tsx
- src/Scrollbar.tsx
- src/Table.tsx
- src/utils/requestAnimationTimeout.ts
- src/utils/toggleClass.ts
- src/utils/translateDOMPositionXY.ts
- src/utils/useAffix.ts
- src/utils/useCellDescriptor.ts
- src/utils/useIsomorphicLayoutEffect.ts
- src/utils/usePosition.ts
- src/utils/useScrollListener.ts
- src/utils/useTableDimension.ts
- src/utils/useTableRows.ts
- test/TableSpec.js
- test/utils.js
* **animation:** remove webkitRequestAnimationFrame ([#22](https://github.com/rsuite/dom-lib/issues/22)) ([69dbbb1](https://github.com/rsuite/dom-lib/commit/69dbbb17a54cf1dfb3a7dee65e6ce4069c578982))
* **deps:** add @babel/runtime ([#25](https://github.com/rsuite/dom-lib/issues/25)) ([b40f9e5](https://github.com/rsuite/dom-lib/commit/b40f9e5e2d965115c1fa8f30e294cc4665e82826))
* **query:** add support for isFocusable ([#23](https://github.com/rsuite/dom-lib/issues/23)) ([eee920a](https://github.com/rsuite/dom-lib/commit/eee920ac0efe5670762734d16c14c2117c48f053))
> build(deps): bump dom-lib to 3.0.0

- src/Scrollbar.tsx
- src/Table.tsx
- src/constants.ts
- src/utils/index.ts
- src/utils/isSupportTouchEvent.ts
- src/utils/usePosition.ts
- src/utils/useScrollListener.ts
fix https://github.com/rsuite/rsuite-table/issues/155
before
https://user-images.githubusercontent.com/1203827/141289131-3fd36911-e076-48c1-9a37-84da1677c6b0.mp4
after
https://user-images.githubusercontent.com/1203827/141289367-b9d24afd-a6c3-4f54-a155-2c79cfe34739.mp4
> feat(Touch): support momentum scroll when touch

- docs/index.tsx
- docs/md/BigTreeTable.md
- src/Table.tsx
- src/constants.ts
- src/utils/findAllParents.ts
- src/utils/flattenData.ts
- src/utils/shouldShowRowByExpanded.ts
- test/TableSpec.js
fix https://github.com/rsuite/rsuite/issues/839
> perf(TreeTable): improve the performance of tree table

- package-lock.json
- package.json
- src/utils/useTableDimension.ts
https://github.com/que-etc/resize-observer-polyfill/issues/80
> build(deps): use @juggle/resize-observer instead of resize-observer-polyfill

- docs/index.tsx
- docs/md/ColumnGroupTable.md
- docs/md/CustomColumnTable.md
- docs/md/CustomColumns.md
- docs/md/EmptyDataTable.md
- docs/md/HideTableHeader.md
- package-lock.json
- package.json
- src/Table.tsx
- src/utils/getTableColumns.ts
- src/utils/useCellDescriptor.ts
- test/TableSpec.js
> fix(scrollbar): enhanced verification of the number of columns

- src/Table.tsx
- src/utils/useTableRows.ts
- test/TableSpec.js
> fix(tree): fix unrecalculated row height after tree node is expanded

- src/utils/getTableColumns.ts
- test/TableSpec.js
table columns support `ColumnGroup` inside `Fragment`
```jsx
<Table>
<>
<ColumnGroup>
<Column>
<HeaderCell />
<Cell />
</Column>
</ColumnGroup>
</>
</Table>
```
> refactor: getTableColumns recursive

- src/Cell.tsx
- src/ColumnGroup.tsx
- src/HeaderCell.tsx
- src/utils/getTableColumns.ts
- src/utils/mergeCells.tsx
- test/ColumnGroupSpec.js
- test/TableSpec.js
fix: https://github.com/rsuite/rsuite-table/issues/280
> fix(Column): fix alignment is overwritten in ColumnGroup

- src/Table.tsx
> fix: fix rowSpan is invalid in ie brower

- src/utils/isSupportTouchEvent.ts
fix https://github.com/rsuite/rsuite/issues/2287
> fix(ssr): fix `window` is not defined for Table Columns

- src/utils/useScrollListener.ts
fix https://github.com/rsuite/rsuite-table/issues/304
> fix(useScrollListener): can't perform a React state update on an unmounted component

- package-lock.json
- package.json
- src/Table.tsx
fix https://github.com/rsuite/rsuite-table/issues/151
> fix(ssr): fix server-side rendering warning

- src/Table.tsx
Extract `data` default value `[]` as constant
Avoid triggering effects that depend on `data`
closed #318
> fix(rerender): fix table infinite rerender

- src/utils/useScrollListener.ts
fix https://github.com/rsuite/rsuite/issues/2378
> fix(scroll): fix horizontal scroll position exception

- src/Table.tsx
- test/TableSpec.js
fix when the Fragment is used, the fix fails
> fix: fix when the Fragment is used, the fix fails

- docs/index.tsx
- docs/less/index.less
- docs/md/ColumnGroupTable.md
- docs/md/CustomColumns.md
- docs/md/RowspanTable.md
- src/Table.tsx
- src/less/table.less
- test/TableSpec.js
fix https://github.com/rsuite/rsuite/issues/2423
Before
After
> fix(Column): fix rowSpan cell layer covering fixed columns

- docs/md/Expanded.md
- src/Table.tsx
- test/TableSpec.js
fix https://github.com/rsuite/rsuite/discussions/2453
fix https://github.com/rsuite/rsuite-table/issues/342
fix https://github.com/rsuite/rsuite-table/issues/345
> fix(Table): fix classPrefix bug due to context parameter

- docs/Examples.tsx
- src/utils/useTableDimension.ts
- test/TableSpec.js
fix: https://github.com/rsuite/rsuite/issues/2315
Before
After
> fix(autoHeight): fix table height calculation error when autoHeight

- docs/md/UpdateData.md
- src/Scrollbar.tsx
- src/Table.tsx
- src/utils/useTableDimension.ts
Only for react 18
https://user-images.githubusercontent.com/1203827/188788277-2e8b301a-4363-4e36-a76c-0a637b87a562.mp4
> fix(Table): fix virtualized table scrolling exception

- package.json
- pnpm-lock.yaml
@simonguo this is the corresponding rsuite-table pr for https://github.com/rsuite/dom-lib/pull/48 (thanks for merging that in!)
> chore: upgrades dom-lib to latest version in order to pull in fix for horizontal scroll on mouse wheel + shiftKey

- docs/examples/LoadingTable.md
- docs/index.tsx
- src/Loader.tsx
- test/TableSpec.js
fix https://github.com/rsuite/rsuite-table/issues/368
> fix(Loader): fix custom loader always showing

- src/less/table.less
- src/less/variables.less
fix: https://github.com/rsuite/rsuite-table/issues/384
> fix(Row): fix the style error of header hover

- docs/examples/Virtualized.md
- src/utils/useScrollListener.ts
fix: https://github.com/rsuite/rsuite-table/issues/381
fix: https://github.com/rsuite/rsuite/issues/2809
> fix(Table): fix virtualized table white screen issue in react 18

- docs/examples/CustomCellTable.md
- docs/examples/CustomColumnTable.md
- docs/index.tsx
- src/utils/getColumnProps.ts
- src/utils/getTotalByColumns.ts
- src/utils/useCellDescriptor.ts
- test/TableSpec.js
```tsx
const CustomColumn = React.forwardRef((props, ref) => {
return <Column ref={ref} sortable align="center" flexGrow={1} fullText {...props} />;
});
const App = () => {
return (
<Table
height={400}
data={data}
>
<CustomColumn align="left">
<HeaderCell>Id</HeaderCell>
<Cell dataKey="id" />
</CustomColumn>
<CustomColumn fixed>
<HeaderCell>First Name</HeaderCell>
<Cell dataKey="firstName" />
</CustomColumn>
</Table>
);
};
```
fix: https://github.com/rsuite/rsuite-table/discussions/344
> fix(Column): fix cannot customize columns

- docs/components/Header/Header.tsx
> docs(Header): add version number

- src/utils/useCellDescriptor.ts
fix: https://github.com/rsuite/rsuite-table/issues/398
https://user-images.githubusercontent.com/1203827/220567037-9533f562-e1fc-4c06-a00a-c790db989798.mp4
https://user-images.githubusercontent.com/1203827/220567114-11aff309-84be-441e-9ba2-de84eae11978.mp4
> fix(resizable): fix scrollbar not showing after resizing column width

- .codesandbox/ci.json
- docs/components/Brand.tsx
- docs/examples/TreeTable.md
- docs/examples/UpdateData.md
- src/Scrollbar.tsx
- src/Table.tsx
- src/less/table.less
- src/utils/defer.ts
- src/utils/index.ts
- src/utils/usePosition.ts
- src/utils/useScrollListener.ts
- src/utils/useTableDimension.ts
- src/utils/useTableRows.ts
fix: https://github.com/rsuite/rsuite-table/issues/405
fix: https://github.com/rsuite/rsuite-table/issues/404
> fix(Table): fix column misalignment after data update

- src/utils/flattenData.ts
Fixed flattenData inner function loop. Previous function implementation was often caused an error **Cannot add property Symbol(parent), object is not extensible**
Fixed ts types
> fix(Table): fix flattenData function

- src/utils/flattenData.ts
Reverts rsuite/rsuite-table#413
> Revert "fix(Table): fix flattenData function"

- docs/examples/FixedColumnTable.md
- src/less/table.less
fix: https://github.com/rsuite/rsuite-table/issues/406
> https://codesandbox.io/s/trusting-knuth-pcrnmx
> fix(Table): fix cell border not showing

- docs/examples/SortTable.md
- docs/index.tsx
- src/Cell.tsx
- src/utils/mergeCells.tsx
- test/SortTableSpec.js
fix: https://github.com/rsuite/rsuite/issues/3169
> fix(ColumnGroup): fix `renderSortIcon` is not working in grouped columns

- docs/examples/LoadingTable.md
- docs/index.tsx
> docs: use placeholder when loading

- src/Cell.tsx
- src/CellGroup.tsx
- src/Column.tsx
- src/ColumnGroup.tsx
- src/ColumnResizeHandler.tsx
- src/EmptyMessage.tsx
- src/HeaderCell.tsx
- src/Loader.tsx
- src/MouseArea.tsx
- src/Row.tsx
- src/Scrollbar.tsx
- src/Table.tsx
- src/TableContext.tsx
Added 'use client' to all components to make them compatible with Next.js 13
> feat(Next.js): add 'use client' to all components

- src/utils/usePosition.ts
- src/utils/useTableDimension.ts
- test/TableSpec.js
fix: https://github.com/rsuite/rsuite-table/issues/451
> fix(Table): fix table scroll width not excluding scroll bar width

- src/Table.tsx
- src/utils/useScrollListener.ts
- test/TableSpec.js
Associated feature request https://github.com/rsuite/rsuite-table/issues/428
> feat(Table): support table scrolling through keyboard arrow keys

- docs/examples/DraggableTable.md
fix: https://github.com/rsuite/rsuite-table/issues/487
> docs(example): fix sort error when dragging rows

- .github/workflows/size-limit.yml
- package.json
- pnpm-lock.yaml
- webpack.build.config.js
- Add webpack.build.config.js for production build
- Add size-limit to check bundle size (limit: 50kB)
- Add GitHub Actions workflow for size check on PRs
> build: add size-limit check and production build config
