- src/Table.js
fixn `randerRowData` to `renderRowData` in `Table.js`
> Fix spelling mistakes

- src/Table.js
- test/TableSpec.js
```js
<Table rowClassName="custom-row" />
// or
<Table rowClassName={(rowData)=>{
if(rowData && rowData.status==='error'){
return 'error-row'
}
}} />
```
feature request: https://github.com/rsuite/rsuite/issues/257
> Support `rowClassName` on Table

- src/Scrollbar.js
When the mouse clicks the left button on the scroll bar, then moves the mouse to the outside of the browser, release the left mouse button, and the event of the scroll bar is not unbound.
Fix: https://github.com/rsuite/rsuite/issues/725
> Fix move scrollbar issues

- src/Table.tsx
修复如下用例中，`rs-table-cell-last` 类渲染在了错误的列上的问题。
```
<Table>
<Column />
{columns.map(column => (
<Column />
)}
<Column />
</Table>
```
> fix: 修复 children 存在 Column 数组时, cell-last 判断可能有误的问题

- README.md
- src/Table.d.ts
- src/Table.tsx
Hello, thank you for writing such a great table library.
If you don't mind, I had a small addition to support optional context menus on rows.  It's a new property onRowContextMenu, and it behaves much like onRowClick.
Would very much appreciate your time in reviewing this, it would allow us to improve our UX for some of our applications.
best,
-Kirat
> feat(OnRowContextMenu): Add an optional onRowContextMenu property

- src/HeaderCell.d.ts
- src/HeaderCell.tsx
In the latest version (3.14.0), the typescript compiler returns an error because the typing of the prop `children` is missing in the HeaderCell component
> fix(HeaderCell): missing children prop type

- docs/md/ColumnGroupTable.md
- src/Cell.tsx
- src/CellGroup.tsx
- src/ColumnGroup.tsx
- src/ColumnResizeHandler.tsx
- src/HeaderCell.tsx
- src/Row.tsx
- src/Table.tsx
- src/TableContext.tsx
- src/utils/index.ts
- src/utils/mergeRefs.ts
- src/utils/prefix.ts
- test/TableSpec.js
fix https://github.com/rsuite/rsuite/issues/1584
fix https://github.com/rsuite/rsuite-table/issues/205
> fix: Fix `classPrefix` cannot be rendered to child elements on `<Table>`

- package-lock.json
- package.json
> build(deps): bump element-resieze-event from 3.0.2 to 3.0.6

- docs/md/WordWrapTable.md
- src/utils/useTableDimension.ts
precondition https://github.com/rsuite/rsuite-table/pull/246
fix https://github.com/rsuite/rsuite/issues/823
fix https://github.com/rsuite/rsuite/issues/1682
> fix(table): fix that `flexGrow` and `wordWrap` cannot be used together

- README.md
- docs/md/TreeTable.md
- src/Table.tsx
- src/utils/useScrollListener.ts
- src/utils/useTableDimension.ts
- test/TableSpec.js
```ts
/**
* Use the return value of `shouldUpdateScroll` to determine
* whether to update the scroll after the table size is updated.
*/
shouldUpdateScroll?:
| boolean
| ((event: 'bodyHeightChanged' | 'bodyWidthChanged' | 'widthChanged') => {
x?: number;
y?: number;
});
```
> feat(Table): added support function type for shouldUpdateScroll

- src/Table.tsx
- src/utils/useScrollListener.ts
- test/TableSpec.js
修复table重渲染时，重置横向滚动条
fix https://github.com/rsuite/rsuite/issues/2140
> fix(scrollbar): fix scroll left reset

- src/utils/getTableColumns.ts
- test/TableSpec.js
嵌套数组中的 `Fragment` 未渲染
```jsx
<Table>
<Column>{...}</Column>,
{[
<Column>{...}</Column>,
[
<>
<Column>{...}</Column>
</>
]
]}
</Table>
```
第三列未展示
递归处理 `children` 中的数组
> fix(Columns): fix Fragment render in nested array

- docs/md/AutoHeightTable.md
- src/utils/useTableDimension.ts
- test/TableSpec.js
fix: https://github.com/rsuite/rsuite-table/issues/300
The table does not have vertical scroll bars when autoHeight is used. At the same time, the scrolling range of the horizontal scroll bar should exclude the width occupied by the vertical scroll bar.
> fix(Table): fix horizontal scroll can not scroll to the end

- src/utils/useTableDimension.ts
It is allowed in interface to pass rowHeight as function, but really it will not work correctly.
Error is reproduced when Table is hidden. Function 'getHeight' from dom-lib returns 0 in that case and rowHeight is using to calculate nextContentHeight. It works fine for numbers, but fails for functions.
> rowHeight using is fixed in useTableDimension

- src/Table.tsx
- src/utils/findRowKeys.ts
- src/utils/flattenData.ts
- src/utils/usePosition.ts
- src/utils/useScrollListener.ts
- src/utils/useTableDimension.ts
- src/utils/useTableRows.ts
Mark `data` prop of Table as readonly array so that readonly arrays can fit.
> refactor: mark array arguments as readonly where they wont be modified

- docs/md/AutoHeightTable.md
- src/utils/useScrollListener.ts
The value of autoHeight changing from false to true after the Table is mounted will cause the scroll event not to update, and vertical scrolling will still work, but it should be blocked.
> fix(autoHeight): fixed scroll event not updating after autoHeight value changed

- src/utils/useCellDescriptor.ts
- test/useCellDescriptorSpec.js
Hi,
First off, thanks for a great table component.
We're using rsuite-table in kinda complex data table based experiences.
As part of these experiences one of our features control column widths through controls that are external to the table component (i.e. not through the resize handler). 
The problem we're facing is that if a user changes the width of a column by using the column resize handler, then takes some action elsewhere which causes the column's width to change (i.e. re-rendered with different prop), the updated `column.width` prop that is passed to rsuite-table will not be honored. This happens due to the caching of column widths within rsuite-table which kicks in once the resize handler is used.
The caching probably makes perfect sense in most cases, but for our use case it …
> fix: reset columnWidths ref when children change in useCellDescriptor

- docs/examples/CustomColumnTable.md
https://github.com/rsuite/rsuite-table/issues/373
> docs(resizable): set a controlled width for resizable columns

- src/Table.tsx
translate3d causes multiple rendering issues when enabled.
https://github.com/rsuite/rsuite-table/issues/98
https://github.com/rsuite/rsuite/issues/1038
https://github.com/rsuite/rsuite-table/issues/256
https://github.com/rsuite/rsuite-table/issues/355
https://github.com/rsuite/rsuite/issues/2648
https://github.com/rsuite/rsuite/discussions/3122
> fix(Table): translate3d disabled by default

- src/utils/useCellDescriptor.ts
Fixed didn't update fluid width when table was mounted
> Fixed didn't update fluid width when table was mounted

- docs/examples/ResizableColumnTable.md
- src/utils/useCellDescriptor.ts
- test/TableSpec.js
this pull request enables the user to define both `resizable` and `flexGrow` properties within a single column
defining both of these properties within the same column results in the column being incapable of resizing and failing to fill the remaining space.
the column needs to be both resizable and fill up any remaining space.
there are empty space in the right
```tsx
<Column width={200} resizable flexGrow={1}>
<HeaderCell>City</HeaderCell>
<Cell dataKey="city" />
</Column>
```
`city` column fills remaining space with no empty space on the right.
> Feat(column): add support for flexGrow with resizable

- docs/examples/ResizableColumnTable.md
- src/utils/useCellDescriptor.ts
1. Implemented resizable column width feature, allowing users to control the width of columns as needed.
2. Fixed the issue where column width was being reset after updating the contents of the column's children, ensuring that column resizing remains consistent.
3. If both `width` and `onResize` are valid, the column will be fully controlled, and `flexGrow` will no longer affect the result.
Setting `width` as a fixed number (e.g., number literal `100`) along with `resizable` and `onResize` simultaneously will make the column width unchangeable.
```tsx
<Table.Column
width={100} // you cant resize it anymore
resizable
onResize={(width) => {
// do something
}}
>
<Table.HeaderCell>name</Table.HeaderCell>
<Table.Cell dataKey="name" />
</Table.Column>
```
```jsx
function App() {
// initial …
```
> [column]: fix column width reset after children update

- src/HeaderCell.tsx
```
node_modules/rsuite-table/lib/HeaderCell.d.ts:4:18 - error TS2430: Interface 'HeaderCellProps' incorrectly extends interface 'InnerCellProps'.
Types of property 'onResize' are incompatible.
Type '((columnWidth?: number | undefined, dataKey?: string | undefined) => void) | undefined' is not assignable to type 'ReactEventHandler<HTMLElement> | undefined'.
Type '(columnWidth?: number | undefined, dataKey?: string | undefined) => void' is not assignable to type 'ReactEventHandler<HTMLElement>'.
Types of parameters 'columnWidth' and 'event' are incompatible.
Type 'SyntheticEvent<HTMLElement, Event>' is not assignable to type 'number'.
4 export interface HeaderCellProps extends InnerCellProps {
~~~~~~~~~~~~~~~
```
> Fix type extension

- src/Table.tsx
fix: https://github.com/rsuite/rsuite-table/issues/443
fix: https://github.com/rsuite/rsuite-table/issues/438
> fix(TreeTable): fix incorrect scrolling position of tree nodes after collapse

- README.md
- src/Table.tsx
- test/TableSpec.js
https://github.com/rsuite/rsuite-table/issues/471
```tsx
const table = useRef();
return (
<Table ref={table} >
...
</Table>
)
// The scroll position of the table
table.current?.scrollPosition
```
> feat(Table): support get scroll position of the table through ref

- README.md
- docs/examples/Virtualized.md
- package.json
- pnpm-lock.yaml
- src/Cell.tsx
- src/Column.tsx
- src/HeaderCell.tsx
- src/Table.tsx
- src/utils/children.ts
- src/utils/getColumnProps.ts
- src/utils/getTotalByColumns.ts
- src/utils/useCellDescriptor.ts
- test/Table.test.tsx
- test/TableSpec.js
> Make Cell & HeaderCell generic

- docs/examples/FluidColumnTable.md
- docs/index.tsx
- package.json
- pnpm-lock.yaml
- src/utils/useIntersectionObserver.ts
- src/utils/useTableDimension.ts
- test/Table.test.tsx
Use the [IntersectionObserver](https://developer.mozilla.org/zh-CN/docs/Web/API/IntersectionObserver) API to listen to whether the table is displayed. If the table is displayed, recalculate the column width.
> fix(Table): fix `flexGrow` is invalid when the table is hidden and then shown

- README.md
- docs/data/mock.ts
- docs/examples/AffixHorizontalScrollbar.md
- docs/examples/AffixTable.md
- docs/examples/AutoHeightTable.md
- docs/examples/BigTreeTable.md
- docs/examples/FillHeightTable.md
- docs/examples/LoadingTable.md
- docs/examples/TreeTable.md
- docs/index.tsx
- package.json
- pnpm-lock.yaml
- src/Table.tsx
- src/utils/index.ts
- src/utils/useClassNames.ts
- src/utils/useScrollListener.ts
- src/utils/useTableData.ts
- src/utils/useTableDimension.ts
- test/TableHeightSpec.js
- test/TableSpec.js
`autoHeight` will automatically calculate the height of the table according to the number of data rows, and there will be no vertical scroll bar. You can set the maximum height through `maxHeight`. When the data exceeds the maximum height, a scroll bar will appear.
```tsx
<Table autoHeight maxHeight={600} >
```
Example: https://rsuite-table-git-feat-table-maxheight-rsuite.vercel.app/#automatic-height
> Requirement comes from: https://github.com/rsuite/rsuite/issues/1727
> feat(Table): add support for `maxHeight` prop

- .eslintrc.js
- karma.conf.js
- package.json
- pnpm-lock.yaml
- src/Cell.tsx
- src/Column.tsx
- src/ColumnGroup.tsx
- src/HeaderCell.tsx
- src/Table.tsx
- src/utils/children.ts
- src/utils/getTableColumns.ts
- src/utils/react-is.ts
- test/ScrollbarSpec.js
- test/TableSpec.js
- test/utils.js
This pull request includes several changes across various files to update dependencies, remove `prop-types`, and clean up code. The most important changes include updating dependencies in `package.json` and `pnpm-lock.yaml`, removing `prop-types` from multiple components, and replacing `react-is` with custom utility functions.
* Updated `@rsuite/icons` to version 1.3.0 in `package.json` and `pnpm-lock.yaml` [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L44-R51) [[2]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL18-R19).
* Updated peer dependencies for `react` and `react-dom` to version 18 in `package.json`.
* Removed `prop-types` from `src/Cell.tsx`, `src/Column.tsx`, `src/ColumnGroup.tsx`, `src/HeaderCell.tsx`, …
> refactor: remove propTypes

- .github/workflows/size-limit.yml
- package.json
- pnpm-lock.yaml
- webpack.build.config.js
This pull request introduces a new workflow to monitor the size of the production build and integrates the necessary dependencies and configurations. The most important changes include adding a GitHub Actions workflow for size limit checks, updating the `package.json` with new scripts and dependencies, and configuring Webpack for production builds.
* [`.github/workflows/size-limit.yml`](diffhunk://#diff-0e6e5ca89e96a26ead6e3deb4656444c810f6ba3838a573084d9f2ba78c0395aR1-R24): Added a new workflow to check the size limit of the production build on pull requests to the `main` and `next` branches.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R11-R19): Added new scripts `dist:pro` and `size` to build the production bundle and check its …
> ci: add size-limit

- package.json
- pnpm-lock.yaml
- src/Table.tsx
- src/utils/children.ts
- src/utils/getTableColumns.ts
- src/utils/react-is.ts
This pull request focuses on removing the dependency on `react-is` and replacing its functionality with custom utility functions. Additionally, it updates the project dependencies accordingly. The most important changes include modifications to the `package.json`, `pnpm-lock.yaml`, and several source files to implement the new utility functions.
Dependency updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L48-R48): Removed `react-is` from dependencies and `@types/react-is` from devDependencies. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L48-R48) [[2]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L82)
* …
> refactor: update table utils and dependencies
